services:
  db:
    image: mysql:8.0
    container_name: adonis_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_localmp
    ports:
      - '6033:3306'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
